# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16.14
    - run: npm ci
    
    - name: Install jq
      run: sudo apt-get install -y jq
      
    - name: 🔎 Send to Algolia
      uses: actions/checkout@v2

    - name: Get the content of algolia.json as config
      id: algolia_config
      run: echo "::set-output name=config::$(cat algolia.json | jq -r tostring)"

    - name: Push indices to Algolia
      uses: signcl/docsearch-scraper-action@master
      env:
        APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
        API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
        CONFIG: ${{ steps.algolia_config.outputs.config }}
      